version: '3'
name: 'time-d-api'
services:
  time-d-api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - time-d-postgres
      - time-d-redis
    links:
      - time-d-postgres
      - time-d-redis
    volumes:
      - ./:/home/node/app
    command: npm run start

  time-d-postgres:
    image: postgres:11
    restart: always

    ports:
      - 3303:5432

    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}

  time-d-redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - '6379:6379'

  time-d-minio:
    hostname: time-d-minio
    image: minio/minio:RELEASE.2021-09-18T18-09-59Z
    container_name: time-d-minio

    volumes:
      - './time-d/data/:/data'
      - './time-d/config:/root/.minio'

    ports:
      - 5003:9000
      - 5004:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001"  /data

  time-d-createbuckets:
    image: minio/mc
    depends_on:
      - time-d-minio
    entrypoint: >
      /bin/sh -c " sleep 10; /usr/bin/mc config host add data http://${MINIO_HOST}:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; /usr/bin/mc mb data/${MINIO_BUCKET}; /usr/bin/mc policy set public data/${MINIO_BUCKET}; exit 0; "
