version: '3'
name: 'time-d-api'
services:
  time-d-api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - time-d-postgres
    links:
      - time-d-postgres
    volumes:
      - ./:/home/node/app
    command: npm run start

  time-d-postgres:
    image: postgres:11
    restart: always

    ports:
      - 3303:5432

    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'wishlist'

  time-d-minio:
    hostname: time-d-minio
    image: minio/minio:RELEASE.2021-09-18T18-09-59Z
    container_name: time-d-minio

    volumes:
      - './time-d/data/:/data'
      - './time-d/config:/root/.minio'

    ports:
      - 5003:9000
      - 5004:9001
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
    command: server --console-address ":9001"  /data

  time-d-createbuckets:
    image: minio/mc
    depends_on:
      - time-d-minio
    entrypoint: >
      /bin/sh -c " sleep 10; /usr/bin/mc config host add data http://localhost:9000 kJ6jEddofBDb4Wd5X6f3 SwF4kykOo0dok3h21lYyJfkQICt0cxsqKS7OusaL; /usr/bin/mc mb data/wishlist; /usr/bin/mc policy set public data/wishlist; exit 0; "
